### ISSUE TITLE
Как насчёт использовать проекты?

### ISSUE THREAD

**Issue by DarkVessel** [ClintFlames/HIVE-DISCUSSION#3]
хочетса видеть планы на будущее и так далее
![изображение](https://user-images.githubusercontent.com/48821354/133936098-7cff63a4-c334-48ca-8f26-478c20035381.png)

**Comment by ClintFlames** [comment]
Щяс бы еще понять что это такое и как ими пользоваться.

**Comment by DarkVessel** [comment]
Они позволяют организовать проекты. Это просто мини-карточки которые ты можешь использовать как хочешь
Делаешь группы ( или выбираешь шаблон как у меня: "to do", "in progress", "done" )
![изображение](https://user-images.githubusercontent.com/48821354/134039422-929d533d-30ab-452b-ba5f-9205d7f8a2ab.png)
![изображение](https://user-images.githubusercontent.com/48821354/134039497-c8aa1aa0-fa66-4f94-9212-283ed1425dc3.png)
![изображение](https://user-images.githubusercontent.com/48821354/134039543-9485c574-65c4-43ff-a8ad-0050747e712d.png)
![изображение](https://user-images.githubusercontent.com/48821354/134039568-5af55b00-d319-4786-bd43-7980284c0226.png)
